### ISSUE TITLE
Coordinator - database and calendar

### ISSUE THREAD

**Issue by k1kli** [k1kli/hvac-with-agents#5]
- [x] Coordinator connects to database
 - [ ] Coordinator uses hibernate to put objects in and out of the database
 - [ ] Coordinator can update events in google calendar
 - [x] Coordinator can get events from google calendar

**Comment by DLZaan** [comment]
"Coordinator can update events in google calendar" - no longer needed
"Coordinator uses hibernate to put objects in and out of the database" - change to only "Coordinator uses hibernate get the needed objects out of the database"
