### ISSUE TITLE
Coordinator Agent - protocols and activities

### ISSUE THREAD

**Issue by k1kli** [k1kli/hvac-with-agents#6]

**Comment by DLZaan** [comment]
- [ ] change simple Date objects to LocalDateTime
- [ ] add time simulator to coodrinator (this will also mean that room coordinator needs this as well)
- [ ] add sending CFPs for meeting
- [ ] add handling reservation for meeting
- [ ] merge Meeting classes (in ontologies with coordinator) - TBD?
